### PR TITLE
notebook upload

### PR DESCRIPTION
**Pull request by Simone-Bordoni**
The notebook is ready with cleared output. Tell me where to put/send the .md file

### CODE REVIEW

**Comment by AleCandido** [comment]
> Tell me where to put/send the .md file

Markdown files will be automatically generated from the notebook, and they are not strictly required for the publication.

Concerning format, your contribution is good enough on its own :)

**Comment by MatteoRobbiati** [comment]
> > Tell me where to put/send the .md file
> 
> Markdown files will be automatically generated from the notebooks, and they are not strictly required for the publication.
> 
> Concerning format, your contribution is good enough on its own :)

You are right. Simone ask for this because of a discussion we had two days ago, when I asked him to provide me with the md too, because I want to upload it now into the site together with mine :)

**Comment by MatteoRobbiati** [comment]
> The notebook is ready with cleared output. Tell me where to put/send the .md file

You can send the md file to me via e-mail.

**Comment by alecandido** [comment]
This could be interested to have, but there are high chances that it is not compatible with the current Qibo (or it will not in the close future), and it's definitely stale.

I'm closing this for the time being. In case, open a new PR, even restarting from the content of this one.

**Pull request closed without merging**
