### PR TITLE
Adding qibocal and qibolab tutorial for NTU

### PR DESCRIPTION
**Pull request by andrea-pasquale**

### CODE REVIEW

**Review by alecandido — APPROVED** [review]

**Comment by alecandido** [comment]
@stavros11 @andrea-pasquale @Edoardo-Pedicillo given that the tutorial worked, I'd just merge this, and possibly keep improving later on.

**Comment by andrea-pasquale** [comment]
Shall we also generate the pdf? I don't know if people are familiar with slidev...

**Comment by stavros11** [comment]
Thanks @andrea-pasquale, I agree with merging and then we can share the link of this repo on matrix. I just pushed two small fixes I noticed with the code highlighting and moved the qibolab notebook in a different directory, so that it's not together with the slidev files.

> Shall we also generate the pdf? I don't know if people are familiar with slidev...

That would probably be very useful.

**Review by stavros11 — APPROVED** [review]

**Comment by alecandido** [comment]
I'm merging: please generate the PDF as well and push them to another PR

**Pull request merged**
